import os
from pathlib import Path

LINK_PROJECT = Path(os.path.abspath(__file__))
LINK_PROJECT = LINK_PROJECT.parent.parent
#print(LINK_PROJECT)
# data 3 is the main one
DATA_LOCATION = "data_task/data_1000_tasks/" 
DATA_DIR = os.path.join(LINK_PROJECT, "data")
RESULT_DIR = os.path.join(LINK_PROJECT, "result/result1/")
DATA_TASK = os.path.join(LINK_PROJECT, DATA_LOCATION)
COMPUTATIONAL_CAPACITY_900 = 2 # Ghz
COMPUTATIONAL_CAPACITY_901 = 2 # Ghz
COMPUTATIONAL_CAPACITY_902 = 2 # Ghz
COMPUTATIONAL_CAPACITY_903 = 2
COMPUTATIONAL_CAPACITY_904 = 2
COMPUTATIONAL_CAPACITY_905 = 2
COMPUTATIONAL_CAPACITY_906 = 2
COMPUTATIONAL_CAPACITY_907 = 2
COMPUTATIONAL_CAPACITY_LOCAL = 4 # Ghz
COMPUTATIONAL_CAPACITY_CLOUD = 500 # Ghz
TRANS_RATE_EDGE_TO_CLOUD = 2 # Mbps
CHANNEL_BANDWIDTH = 20 # MHz
List_COMPUTATION = [COMPUTATIONAL_CAPACITY_900, COMPUTATIONAL_CAPACITY_901, COMPUTATIONAL_CAPACITY_902, 
                    COMPUTATIONAL_CAPACITY_903, COMPUTATIONAL_CAPACITY_904, COMPUTATIONAL_CAPACITY_905,
                    COMPUTATIONAL_CAPACITY_906, COMPUTATIONAL_CAPACITY_907, COMPUTATIONAL_CAPACITY_LOCAL]
# Pr = 46 # dBm
Pr = 46
P = 39.810 # mW
SIGMASquare = 100 # dBm   background noise power
PATH_LOSS_EXPONENT = 3.25  # alpha
NUM_VEHICLE = 5
NUM_EDGE_SERVER = NUM_VEHICLE + 1 # a server + vehicles
NUM_STATE = NUM_EDGE_SERVER * 2 + 2
NUM_ACTION = NUM_EDGE_SERVER + 1 # including cloud, must + 1
SCAILING_CO_EFFICIENT = 1
FILE_NAME = "Not change"
NB_STEPS = 81000
#NB_STEPS = 405000
class Config:
    Pr = 46
    Pr2 = 24
    Wm = 10
    length_hidden_layer=4
    n_unit_in_layer=[16, 32, 32, 8]
